# EdenFS: the virtual filesystem daemon (`edenfs`), its privilege helper
# (`edenfs_privhelper`) and the `edenfsctl` CLI (Rust front-end with a Python
# fallback), built through the repository's top-level CMake project like
# getdeps does (see build/fbcode_builder/manifests/eden).
{
  lib,
  stdenv,
  callPackage,
  rustPlatform,
  cmake,
  ninja,
  pkg-config,
  cargo,
  rustc,
  cxx-rs,
  python3,
  makeWrapper,
  runCommand,

  # Used by the CLI for `eden clone` & co. (see saplingForEden below).
  sapling,

  fbStack,

  boost,
  cpptoml,
  curl,
  double-conversion,
  fmt,
  gflags,
  glog,
  gtest,
  libblake3,
  libevent,
  libgit2,
  libselinux,
  libsepol,
  libsodium,
  libunwind,
  liburing,
  lmdb,
  lz4,
  openssl,
  re2,
  snappy,
  sqlite,
  xxhash,
  xz,
  zlib,
  zstd,
}:

let
  inherit (fbStack)
    folly
    fizz
    wangle
    mvfst
    fbthrift
    fb303
    edencommon
    thrift1
    ;

  version = "0-unstable-2026-09-30";

  pythonRuntime = callPackage ./python-runtime.nix { inherit fbStack; };

  # All Rust code is built from the eden/fs Cargo workspace (see
  # eden/fs/rust/oss-rust-ffi in oss-build-fixes.patch), which also pulls in
  # the eden/scm crates it needs. Upstream strips Cargo.lock files, so ours
  # lives here.
  cargoDeps = rustPlatform.fetchCargoVendor {
    name = "edenfs-${version}";
    src = lib.fileset.toSource {
      root = ./.;
      fileset = ./Cargo.lock;
    };
    hash = "sha256-kV08GRALtAyOApSCJkrEmRKUoRtc/M8cSY9N7aXVMX4=";
  };

  # The C++ side of the Rust cxx bridges is generated by nixpkgs' `cxxbridge`
  # (cxx-rs), which has to be the exact version of the locked `cxx` crate.
  cxxVersion =
    (lib.findFirst (p: p.name == "cxx") (throw "no cxx in Cargo.lock")
      (lib.importTOML ./Cargo.lock).package
    ).version;

  # Sapling as `eden clone` and checkouts need it: with the `eden` Cargo
  # feature, which ../sapling enables by default (withEdenfs). This is the
  # same package unless someone overrode that.
  saplingForEden = sapling.override { withEdenfs = true; };

  # Private directory on the CLI's PATH: parts of both CLIs run a hardcoded
  # `hg` (e.g. `eden du`), which is Sapling's historical name.
  hgShim = "${placeholder "out"}/libexec/eden/bin";

  # The Python used for the build-time tooling and as the interpreter of the
  # generated `edenfsctl.real` zipapp: carries the CLI's third-party modules.
  pythonEnv = python3.withPackages (ps: [
    ps.filelock
    ps.psutil
    ps.toml
    pythonRuntime.thrift-python
  ]);
in
assert lib.assertMsg (cxx-rs.version == cxxVersion)
  "edenfs: nixpkgs cxx-rs ${cxx-rs.version} does not match the cxx ${cxxVersion} in nix/edenfs/Cargo.lock; update the lock file.";

stdenv.mkDerivation (finalAttrs: {
  pname = "edenfs";
  inherit version;

  # Only what the build reads, so that e.g. edits to Sapling's (large) test
  # suite or docs do not rebuild EdenFS: from eden/scm only the Rust crates
  # the daemon and edenfsctl link, plus the bits its CMakeLists.txt uses.
  src = lib.fileset.toSource {
    root = ../..;
    fileset = lib.fileset.difference (lib.fileset.unions (
      map (p: ../.. + "/${p}") [
        "CMakeLists.txt"
        "CMake"
        "build/fbcode_builder/CMake"
        "common/rust/shed"
        "configerator/structs/scm"
        "eden/fs"
        "eden/mononoke/common/lfs_protocol"
        "eden/scm/CMakeLists.txt"
        "eden/scm/Cargo.toml"
        "eden/scm/exec"
        "eden/scm/lib"
        "eden/scm/sapling/redact.py"
        "eden/test_support"
        "fb303/thrift"
        "thrift/annotation"
        "thrift/lib/rust"
        "watchman/rust"
      ]
    )) ../../eden/fs/docs;
  };

  nativeBuildInputs = [
    cmake
    ninja
    pkg-config
    cargo
    rustc
    rustPlatform.bindgenHook # libsqlite3-sys (edenfsctl)
    cxx-rs # provides `cxxbridge`, see cxxVersion
    fbthrift # thrift compiler for C++ and Python code generation
    pythonEnv
    makeWrapper
  ];

  buildInputs = [
    boost
    cpptoml
    curl
    double-conversion
    edencommon
    fb303
    fbthrift
    fizz
    fmt
    folly
    gflags
    glog
    gtest
    libblake3
    libevent
    libgit2
    libselinux
    libsepol
    libsodium
    libunwind
    liburing
    lmdb
    lz4
    mvfst
    openssl
    re2
    snappy
    sqlite
    wangle
    xxhash
    xz
    zlib
    zstd
  ];

  patches = [
    # Upstream's open source CMake/Cargo build has bit-rotted in places:
    # sources that became header-only or were renamed, Rust cxx bridges that
    # were never wired into CMake, Meta-internal crates (Manifold, the
    # "thriftclients" Thrift flavour) without an open source stand-in, ...
    ./oss-build-fixes.patch
  ];

  postPatch = ''
    # --- Rust ------------------------------------------------------------------

    # Some autocargo-generated manifests give both `path` and `git` for a
    # dependency, which current Cargo rejects as ambiguous. Keep the path.
    find eden -name Cargo.toml -exec \
      sed -i -E '/path = /s/, git = "[^"]*", branch = "[^"]*"//' {} +

    # Replace upstream's fbsource-wide [patch] tables with the ones we locked
    # against: the in-repo fbthrift/fb303/watchman/rust-shed crates, plus the
    # subset of upstream's patches the dependency graph actually uses.
    awk '/^\[/ { skip = ($0 ~ /^\[patch/) } !skip' eden/fs/Cargo.toml > Cargo.toml.new
    mv Cargo.toml.new eden/fs/Cargo.toml
    cat ${./upstream-patches.toml} ${./cargo-patches.toml} >> eden/fs/Cargo.toml
    install -m644 ${./Cargo.lock} eden/fs/Cargo.lock

    mkdir -p eden/fs/.cargo
    substitute ${cargoDeps}/.cargo/config.toml eden/fs/.cargo/config.toml \
      --subst-var-by vendor ${cargoDeps}

    # --- CMake -----------------------------------------------------------------

    # fb303 Python bindings and the CLI's Python deps (see python-deps.cmake).
    cp ${./python-deps.cmake} CMake/NixPythonDeps.cmake
    substituteInPlace CMake/EdenConfigChecks.cmake \
      --replace-fail 'find_package(python-toml REQUIRED)' "" \
      --replace-fail 'find_package(python-filelock REQUIRED)' "" \
      --replace-fail 'find_package(python-psutil REQUIRED)' ""
    substituteInPlace CMakeLists.txt \
      --replace-fail 'add_subdirectory(eden/fs)' $'include(NixPythonDeps)\nadd_subdirectory(eden/fs)' \
      --replace-fail 'add_subdirectory(eden/integration)' ""

    # Nix-specific runtime paths for the Python CLI: there is no
    # /usr/local/libexec or /usr/bin/sudo, and on NixOS setuid wrappers and
    # system binaries live in /run.
    substituteInPlace eden/fs/cli/daemon.py \
      --replace-fail '"/usr/local/libexec/eden/edenfs_privhelper"' "\"$out/libexec/eden/edenfs_privhelper\"" \
      --replace-fail 'sudo_cmd = ["/usr/bin/sudo"]' 'sudo_cmd = ["sudo"]' \
      --replace-fail \
        'path_dirs = ["/opt/facebook/hg/bin", "/usr/local/bin", "/bin", "/usr/bin"]' \
        'path_dirs = ["${hgShim}", "/run/wrappers/bin", "/run/current-system/sw/bin", "/usr/local/bin", "/bin", "/usr/bin"]'

    # New checkouts get the dot-dir of the bundled (open source) Sapling,
    # which only knows `.sl`; upstream defaults to Meta's `.hg`.
    substituteInPlace eden/fs/cli/hg_util.py \
      --replace-fail 'return _possible_dot_dirs[0]' 'return ".sl"'

    # `eden config` (Rust) fails with "field other is missing" when no config
    # file exists at all; give the catch-all table a default like the others.
    substituteInPlace eden/fs/cli_rs/edenfs-config/src/lib.rs \
      --replace-fail '#[stack(merge = "merge_table")]' '#[stack(merge = "merge_table", default)]'

    # Only build the (large) C++ unit test suites when running them.
    find eden -name CMakeLists.txt -exec \
      sed -i -E 's/^(\s*)add_subdirectory\(test\)/\1if(BUILD_TESTING)\n\1  add_subdirectory(test)\n\1endif()/' {} +
  '';

  preConfigure = ''
    export CARGO_HOME=$TMPDIR/cargo-home
    # `curl`'s static-ssl feature would build a vendored OpenSSL.
    export OPENSSL_NO_VENDOR=1
    # Used by the Rust Thrift code generation (thrift_compiler crate); see
    # ../fb-stack.nix.
    export THRIFT=${thrift1}
    # Keep panic locations from referencing (and retaining) the vendor dir.
    export RUSTFLAGS="--remap-path-prefix=${cargoDeps}=/build/cargo-vendor-dir"
    export CARGO_NET_OFFLINE=true
    export CARGO_BUILD_JOBS=$NIX_BUILD_CORES
  '';

  # Upstream's CMake does not order the headers generated for the Rust cxx
  # bridges before all of their (transitive) users, so produce them first.
  preBuild = ''
    ninja -j$NIX_BUILD_CORES backingstore edenfs_ffi redirect_ffi backtrace_ffi
  '';

  # The repository's own build/ directory holds fbcode_builder's CMake modules.
  cmakeBuildDir = "_build";

  cmakeFlags = [
    (lib.cmakeBool "BUILD_TESTING" finalAttrs.doCheck)
    (lib.cmakeFeature "ENABLE_GIT" "ON")
    (lib.cmakeFeature "ENABLE_EDENSCM" "ON")
    (lib.cmakeFeature "USE_CARGO_VENDOR" "OFF")
    (lib.cmakeFeature "RUST_CXX_VERSION" cxxVersion)
    (lib.cmakeFeature "Python3_EXECUTABLE" "${pythonEnv}/bin/python3")
    (lib.cmakeFeature "EDEN_VERSION_OVERRIDE" "20260930.000000.0")
  ];

  # The unit and integration test suites need a FUSE-capable environment.
  doCheck = false;

  postInstall = ''
    # Static libraries, headers and Python library manifests of internal
    # components that upstream's CMake installs.
    rm -r $out/lib $out/eden

    # Match upstream's layout: the CLI looks for the daemon (and the daemon
    # for its privhelper) in <prefix>/libexec/eden.
    mkdir -p $out/libexec/eden
    mv $out/bin/edenfs $out/bin/edenfs_privhelper $out/libexec/eden/
    ln -s ../libexec/eden/edenfs $out/bin/edenfs
    ln -s edenfsctl $out/bin/eden

    # Both CLIs shell out to Sapling: through EDEN_HG_BINARY where they
    # honour it, otherwise as a plain `hg` (Sapling's historical name), so
    # put the shim in front of a Mercurial `hg` that may be on PATH. (The
    # Rust CLI passes its environment on to edenfsctl.real.)
    mkdir -p ${hgShim}
    ln -s ${lib.getExe saplingForEden} ${hgShim}/hg
    ln -s ${lib.getExe saplingForEden} ${hgShim}/sl
    for prog in edenfsctl edenfsctl.real; do
      wrapProgram $out/bin/$prog \
        --set-default EDEN_HG_BINARY ${lib.getExe saplingForEden} \
        --prefix PATH : ${hgShim}
    done
  '';

  passthru = {
    inherit
      cargoDeps
      pythonEnv
      pythonRuntime
      fbStack
      ;
    # The `sl` EdenFS checkouts are used with (see saplingForEden).
    sapling = saplingForEden;

    # Mounting needs FUSE and root, which the Nix sandbox does not have, so
    # this only covers what works without a running daemon.
    tests.smoke = runCommand "edenfs-smoke-test" { } ''
      bash ${./smoke-test.sh} ${finalAttrs.finalPackage}
      touch $out
    '';
  };

  meta = {
    description = "Virtual filesystem for large source control repositories";
    homepage = "https://github.com/facebook/sapling/tree/main/eden/fs";
    license = lib.licenses.gpl2Only;
    mainProgram = "edenfsctl";
    platforms = lib.platforms.linux;
  };
})
