#!/usr/bin/env bash
# Regenerate nix/edenfs/Cargo.lock (the eden/fs Cargo workspace, which also
# pulls in crates from eden/scm) for the current checkout.
#
# Usage: nix/edenfs/update-lockfile.sh [output, default: nix/edenfs/Cargo.lock]
#
# Needs network access. Afterwards, update `cargoDeps.hash` in default.nix
# (build once with `hash = lib.fakeHash;` and copy the reported one).
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../.." && pwd)
out=$(realpath -m "${1:-$here/Cargo.lock}")
# The rust-shed revision the rest of the Meta stack is at (../fb-stack.json).
rust_shed_rev=$(nix eval --raw --impure --expr \
  "(builtins.fromJSON (builtins.readFile $repo/nix/fb-stack.json)).rust-shed.rev")
# The C++ side of the cxx bridges is generated by nixpkgs' cxxbridge, which
# must be the exact version of the `cxx` crate.
cxx_version=$(nix eval --raw --inputs-from "$repo" nixpkgs#cxx-rs.version)

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The parts of the source the Cargo workspace reads (see default.nix).
tar -C "$repo" -cf - build/fbcode_builder/CMake common/rust/shed \
  configerator/structs/scm eden/fs eden/mononoke/common/lfs_protocol \
  eden/scm/Cargo.toml eden/scm/exec eden/scm/lib fb303/thrift thrift/annotation \
  thrift/lib/rust watchman/rust |
  tar -C "$work" -xf -

# The same edits as patches/postPatch in default.nix.
patch -d "$work" -p1 --quiet <"$here/oss-build-fixes.patch"
find "$work/eden" -name Cargo.toml -exec \
  sed -i -E '/path = /s/, git = "[^"]*", branch = "[^"]*"//' {} +
ws=$work/eden/fs
awk '/^\[/ { skip = ($0 ~ /^\[patch/) } !skip' "$ws/Cargo.toml" >"$ws/Cargo.toml.new"
mv "$ws/Cargo.toml.new" "$ws/Cargo.toml"
cat "$here/upstream-patches.toml" "$here/cargo-patches.toml" >>"$ws/Cargo.toml"

# Use the nixpkgs pinned in flake.lock, so the cargo writing the lock is the
# one that builds with it.
nix shell --inputs-from "$repo" nixpkgs#cargo nixpkgs#git -c bash -euo pipefail -c '
  cd "$1"
  export CARGO_HOME=$2/cargo-home CARGO_NET_GIT_FETCH_WITH_CLI=true
  cargo generate-lockfile
  cargo update -p cxx --precise "$4"
  # Pin the rust-shed crates that are not vendored in this repository to the
  # revision getdeps uses. Any of them selects the whole git source.
  cargo update -p sorted_vector_map --precise "$3"
  if grep -q "^\[\[patch.unused\]\]" Cargo.lock; then
    echo "warning: unused [patch] entries; drop them from the patch files:" >&2
    grep -A1 "^\[\[patch.unused\]\]" Cargo.lock | grep "^name" >&2
  fi
' _ "$ws" "$work" "$rust_shed_rev" "$cxx_version"

cp "$ws/Cargo.lock" "$out"
echo "Wrote $out"
